# Generated by Django 4.1 on 2022-08-13 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('push_service_url', models.CharField(max_length=200, verbose_name='Push Service URL')),
                ('subscription_auth', models.CharField(help_text='p256dh client key', max_length=200, verbose_name='Subscription Auth')),
                ('subscription_secret', models.CharField(max_length=100, verbose_name='Subscription Secret')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ('-created_at',),
            },
        ),
    ]
